name: CI for Fibo2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download JUnit JAR
      run: |
        wget https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar -O junit.jar
        wget https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O hamcrest.jar
        wget https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/3.22.0/assertj-core-3.22.0.jar -O assertj-core.jar
        
    - name: Compile Java code
      run: |
        javac -d bin Fibo2/dyasc-2024-main/untref-dyasc-material-main/proyecto-base/src/main/java/ar/edu/untref/dyasc/*.java
        javac -d bin -cp bin Fibo2/dyasc-2024-main/untref-dyasc-material-main/proyecto-base/src/test/java/ar/edu/untref/dyasc/*.java
    
    - name: List compiled files
      run: ls -R bin
      
    - name: Run tests
      run:  java -cp "bin:junit.jar:hamcrest.jar" org.junit.runner.JUnitCore ar.edu.untref.dyasc.FibonacciAppTest
