name: CI for Fibo2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Compile Java code
      run: javac -d bin Fibo2/dyasc-2024-main/untref-dyasc-material-main/proyecto-base/src/main/java/ar/edu/untref/dyasc/FibonacciApp.java
      
    - name: Run tests
      run: java -cp bin org.junit.runner.JUnitCore ar.edu.untref.dyasc.FibonacciAppTest
